# Generated by Django 3.0.7 on 2020-06-06 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='projects.Project')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, related_name='assigned_tickets', to='accounts.Account')),
                ('author', models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, related_name='created_tickets', to='accounts.Account')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.TextField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low')),
                ('status', models.TextField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open')),
                ('type', models.TextField(choices=[('bug', 'Bug'), ('feature_request', 'Feature Request'), ('comment', 'Comment')])),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
